# -*- coding: utf-8 -*-
"""Copy of DJS Compute DA & ML Task 1 2024-25.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1h6xs41lC3YaxBk5SLCbqdDmiafSnr_jW

**General Instructions:**

*   Please make a copy of this colab notebook in your own drive and solve the questions in the copy. Do not edit the original file.

*   All participants are encouraged to learn the basics of python including data types, operators, loops, conditional statements, handling user-defined input, strings, string methods, lists, list comprehension, sets, tuples, dictionaries and basic object-oriented programming concepts before coming to the interview.

Beginners unfamiliar with Python are advised to watch the following tutorial before beginning Task 1.

**Python Tutorial:** https://youtu.be/_uQrJ0TkZlc?feature=shared


**Note:** The expected output is given in the cells below the question.

# Task 1 - Basics of Python



> It is the year 3031 and the Earth has been invaded by an alien species from the planet of Dioneterra. The resources on their own planet have become severely depleted and they're determined to subjugate humans and take control of the Earth's resources. The Dioneterrans can take on the appearance of any human. The world has been thrown into chaos and fear as the aliens have infiltrated all levels of government. You don't know who to trust as anyone can be an alien in disguise.

**Question 1:**
You have a group of people you can trust, whose identities you have confirmed as humans. Unfortunately, since the aliens have access to government resources they have information on all citizens. It would be the height of foolishness to call your team members by their own names while on missions to save humanity. As such you need to generate secret code names for each member.

Given below is a list of names. Your job is to write a function codename_generator() that takes the given list as input and prints every possible combination of code names from the given list, separated by whitespace (e.g. Orion Barracuda). Take care to not print codenames with the same name twice (e.g. Orion Orion) or two codenames with the same combination (e.g. if you have a codename Orion Barracuda, then you cannot have a codename Barracuda Orion).
"""

name_list = ["Orion", "Barracuda", "Amethyst", "Blade", "Wasp", "Nemesis", "Fury", "Cobra", "Tempest", "Leo", "Scythe"]

# your code here
def codename_generator():
    name_list = ["Orion", "Barracuda", "Amethyst", "Blade", "Wasp", "Nemesis", "Fury", "Cobra", "Tempest", "Leo", "Scythe"]

    for i in range(len(name_list)):
        for j in range(i,11):
            if(i==j):
                continue
            else:
                print(f"{name_list[i]} {name_list[j]}")     # Prints the code names

codename_generator()

"""**Question 2:**
You recently caught wind of the rumour that a Resistance Movement against the aliens is starting to gain traction. You and your group of trustworthy humans resolve to go to the headquarters of the Resistance and join the movement.

You reach the headquarters and find utter chaos, the leader of the Resistance tells you that they have so many refugees and as a result their registration system is a mess and they have no way of telling apart actual humans and aliens who might have infiltrated the headquarters as humans.

He knows that you have programming skills and asks for your help in weeding out the aliens.

Given below in the form of a list is the register of names of refugees that the headquarters maintains. Sort the names into two lists - potential aliens and humans. Alien names may:
*   begin with the letter 'G'
*   contain the substring 'arz'
*   contain a digit

Additionally, ensure that the new lists do not contain duplicate names and handle any problems that may arise due to case-sensitivity and whitespaces.


"""

register = ["Gunther", "karzan", "pip1do", "amelia", "emma", "jarzk", "P0ppy", "gunther", "Daisy"," Demelza ", "Lisa ", "garzon ", "marz4"]

# your code here
register = ["Gunther", "karzan", "pip1do", "amelia", "emma", "jarzk", "P0ppy", "gunther", "Daisy"," Demelza ", "Lisa ", "garzon ", "marz4"]
Humans = list()
Aliens = list()
char = {"g","0","1","2","3","4","5","6","7","8","9"}
for i in range(len(register)):
    name = register[i].lower()

    if any ((n in char) for n in name):     # Checks if the name contains any of the characters in char
        Aliens.append(register[i].lower())
    elif "arz" in name:
        Aliens.append(register[i].lower())
    else:
        Humans.append(register[i].lower())

print(Humans)
print(Aliens)

"""**Question 3:** Now that you have identified the potential aliens, its now time to decide how probable it is that these refugees are aliens.

Prepare a dictionary where the keys are the names from the potential aliens list and the associated values are percentages from 0-100 of how probable it is that the refugee with those names are aliens.

Given below are the conditions and associated probabilities:
*   name starts with 'g' - 25%
*   name contains "arz" - 50%
*   name starts with 'g' and contains "arz" - 75%
*   name has a digit - 100%
"""

# your code here

Alien_names = ['gunther', 'karzan', 'pip1do', 'jarzk', 'p0ppy', 'gunther', 'garzon ', 'marz4']

prob = list()
for i in Alien_names:
    if i.startswith("g") and "arz" in i:
        prob.append(75)
    elif i.startswith("g"):
        prob.append(25)
    elif "arz" in i:
        prob.append(50)
    else:
        prob.append(100)

dictionary = dict(zip(Alien_names,prob))    # Merges the two lists into a dictionary
print(dictionary)

"""**Question 4:** Now that you have completely weeded out the aliens, onto the next part of the plan.

There are 12 districts in your city - I to XII. Another resistance group has agreed to share supplies with your group. They send you a list of districts they are operational in and you have in hand, the list of districts your group has members in. Determine which districts you can meet up in, i.e., districts that both the groups operate in.

Hint: set operations may prove useful.
"""

your_districts = ['I', 'IV', 'V', 'I', 'VI', 'IX', 'X', 'II', 'III', 'I']
their_districts = ['V', 'IV', 'VI', 'XII', 'VII', 'IV', 'VI', 'VIII', 'III']

# your code here
your_districts = ['I', 'IV', 'V', 'I', 'VI', 'IX', 'X', 'II', 'III', 'I']
their_districts = ['V', 'IV', 'VI', 'XII', 'VII', 'IV', 'VI', 'VIII', 'III']

d1 = set(your_districts)
d2 = set(their_districts)
meet_up_districts = d1.intersection(d2)     # Gives the common elements in both sets
print(meet_up_districts)

"""Let's take the difficulty up a notch shall we? Your spies have informed you that the alien goverment has been setting up patrols in some districts to curb rebel movement. One of the spies managed to get a list of the districts that are being patrolled. Ensure that your meet up with the other rebel group does not take place in a patrolled district so that you do not get caught."""

patrolled_districts = ['I', 'II', 'XII', 'IX', 'XI', 'IV', 'II', 'VI']

# your code here
patrolled_districts = ['I', 'II', 'XII', 'IX', 'XI', 'IV', 'II', 'VI']
meet_up_districts = ['VI', 'III', 'V', 'IV']

p1 = set(patrolled_districts)
m1 = set(meet_up_districts)
new = m1.difference(p1)     # gives elements in m1 that are not common in p1
print(new)

"""**Question 5:** Given below is a list of tuples. Each tuple in this list contains the rank and the name of a Dioneterran Commander. Your job is to define two functions: sort_by_rank() in descending order and sort_by_name() alphabetically to sort the given list by rank and name, respectively.

Hint: use lambda expressions
"""

commanders = {(4, "Barzak"), (2, "Donesia"), (5, "Zeroza"), (1, "Yggacia"), (3, "Larzon")}

# your code here
commanders = {(4, "Barzak"), (2, "Donesia"), (5, "Zeroza"), (1, "Yggacia"), (3, "Larzon")}
comm = list(commanders)

rank = comm.sort(reverse=True)      # Compares the second element of the tuples i.e the rank
print("Sorted by Rank: ",comm)

name = comm.sort(key = lambda x: x[1])      # Sorts the tuples alphabetically
print("Sorted by Name: ",comm)

"""**Question 6:** You have been given the task of calculating the danger level of Dioneterran Commanders. To accomplish this task, you're required to define a class Commander with the attributes name, rank, weight, height and age. Implement a method calculate_danger() that returns the danger level by adding the height to the weight and dividing the result by the age, round off to the nearest integer.

Create a Commander object with the necessary parameters and print the danger level.
"""

# your code here
class Commander:
    name = "Zeroza"
    rank = 5
    age = 25            # I have assumed these attributes' values as it is not mentioned in the problem statement
    height = 152       # Height is in centimeters
    weight = 60

    def calculate_danger(self):
        danger = int((self.height + self.weight)/self.age)
        return danger

a = Commander()     # Making class object
a.name = "Yggacia"
a.rank = 1
a.age = 26
a.height = 160
a.weight = 60

danger_level = a.calculate_danger()
print("Danger level =",danger_level)

"""**Question 7:** All the refugees in the headquarters who have been confirmed as humans have been assigned an ID. A lock has been installed at the gate. Your job is to write a regular expression that checks whether the ID entered is a valid one. Valid IDs have the following features:
*   They are strings of exactly 7 characters
*   The first 3 characters are uppercase alphabets
*   The other last 4 characters are digits.

Given below is a list of IDs entered at the gate. Determine which ones are valid.


P.S. Don't forget to import the re module
"""

test_ids = ["ABC1234", "sbaz56", "Wuy1452", "TYP9006", "KZED439"]

# your code here
import re

test_ids = ["ABC1234", "sbaz56", "Wuy1452", "TYP9006", "KZED439"]
valid_id = []

for i in test_ids:
    if(re.search("[A-Z][A-Z][A-Z][0-9][0-9][0-9][0-9]",i)):         # [] specifies a character class
        valid_id.append(i)
print("Valid ID's =",valid_id)

"""For a better understanding of Regular Expressions: https://realpython.com/regex-python/"""